name: easysafar
description: "A professional transport booking application for Gilgit-Baltistan routes."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Backend & Database
  supabase_flutter: ^2.0.2

  # UI & Styling
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.6

  # Utilities
  intl: ^0.19.0
  provider: ^6.1.1

  # Image & Storage
  image_picker: ^1.0.7
  url_launcher: ^6.3.2

  # Live Location & Maps
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true